#!/bin/bash

# genman.sh builds application and (re-)generates its man-page

if [[ "$(uname)" == "Darwin" ]]; then
  SED="gsed -i"
else
  SED="sed -i"
fi

mkdir -p build && cd build && cmake .. && make -s && cd .. && \
help2man -n "ncurses mail" -N -o src/nmail.1 ./build/nmail && \
${SED} "s/\.\\\\\" DO NOT MODIFY THIS FILE\!  It was generated by help2man.*/\.\\\\\" DO NOT MODIFY THIS FILE\!  It was generated by help2man./g" src/nmail.1
exit ${?}
